/*
 * This file is generated by jOOQ.
 */
package shop.topup.admin.domain.common.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import shop.topup.admin.domain.common.jooq.tables.Supplier;
import shop.topup.admin.domain.common.jooq.tables.SupplierApiInfo;
import shop.topup.admin.domain.common.jooq.tables.SupplierCatalog;
import shop.topup.admin.domain.common.jooq.tables.SupplierGoods;
import shop.topup.admin.domain.common.jooq.tables.records.SupplierApiInfoRecord;
import shop.topup.admin.domain.common.jooq.tables.records.SupplierCatalogRecord;
import shop.topup.admin.domain.common.jooq.tables.records.SupplierGoodsRecord;
import shop.topup.admin.domain.common.jooq.tables.records.SupplierRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SupplierRecord> SUPPLIER_PKEY = Internal.createUniqueKey(Supplier.SUPPLIER, DSL.name("supplier_pkey"), new TableField[] { Supplier.SUPPLIER.ID }, true);
    public static final UniqueKey<SupplierApiInfoRecord> SUPPLIER_API_INFO_PKEY = Internal.createUniqueKey(SupplierApiInfo.SUPPLIER_API_INFO, DSL.name("supplier_api_info_pkey"), new TableField[] { SupplierApiInfo.SUPPLIER_API_INFO.ID }, true);
    public static final UniqueKey<SupplierCatalogRecord> SUPPLIER_CATALOG_PKEY = Internal.createUniqueKey(SupplierCatalog.SUPPLIER_CATALOG, DSL.name("supplier_catalog_pkey"), new TableField[] { SupplierCatalog.SUPPLIER_CATALOG.ID }, true);
    public static final UniqueKey<SupplierGoodsRecord> SUPPLIER_GOODS_PKEY = Internal.createUniqueKey(SupplierGoods.SUPPLIER_GOODS, DSL.name("supplier_goods_pkey"), new TableField[] { SupplierGoods.SUPPLIER_GOODS.ID }, true);
}
