/*
 * This file is generated by jOOQ.
 */
package shop.topup.admin.domain.common.jooq;


import shop.topup.admin.domain.common.jooq.tables.Supplier;
import shop.topup.admin.domain.common.jooq.tables.SupplierApiInfo;
import shop.topup.admin.domain.common.jooq.tables.SupplierCatalog;
import shop.topup.admin.domain.common.jooq.tables.SupplierGoods;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.supplier</code>.
     */
    public static final Supplier SUPPLIER = Supplier.SUPPLIER;

    /**
     * The table <code>public.supplier_api_info</code>.
     */
    public static final SupplierApiInfo SUPPLIER_API_INFO = SupplierApiInfo.SUPPLIER_API_INFO;

    /**
     * The table <code>public.supplier_catalog</code>.
     */
    public static final SupplierCatalog SUPPLIER_CATALOG = SupplierCatalog.SUPPLIER_CATALOG;

    /**
     * The table <code>public.supplier_goods</code>.
     */
    public static final SupplierGoods SUPPLIER_GOODS = SupplierGoods.SUPPLIER_GOODS;
}
